
package com.revature.cart;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-03-25T16:26:41.653-04:00
 * Generated source version: 3.3.0
 *
 */
public final class CartService_CartServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://cart.revature.com/", "CartService");

    private CartService_CartServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CartService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        CartService_Service ss = new CartService_Service(wsdlURL, SERVICE_NAME);
        CartService port = ss.getCartServiceImplPort();

        {
        System.out.println("Invoking addItem...");
        com.revature.cart.Item _addItem_arg0 = new com.revature.cart.Item();
        java.lang.String _addItem__return = port.addItem(_addItem_arg0);
        System.out.println("addItem.result=" + _addItem__return);


        }
        {
        System.out.println("Invoking removeItem...");
        com.revature.cart.Item _removeItem_arg0 = new com.revature.cart.Item();
        boolean _removeItem__return = port.removeItem(_removeItem_arg0);
        System.out.println("removeItem.result=" + _removeItem__return);


        }
        {
        System.out.println("Invoking itemQuanitity...");
        com.revature.cart.Item _itemQuanitity_arg0 = new com.revature.cart.Item();
        java.lang.String _itemQuanitity_arg1 = "";
        int _itemQuanitity__return = port.itemQuanitity(_itemQuanitity_arg0, _itemQuanitity_arg1);
        System.out.println("itemQuanitity.result=" + _itemQuanitity__return);


        }

        System.exit(0);
    }

}
