package com.revature.cart;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-03-25T16:26:41.911-04:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "CartService",
                  wsdlLocation = "http://localhost:8080/SOAPGreeting/cartService?wsdl",
                  targetNamespace = "http://cart.revature.com/")
public class CartService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cart.revature.com/", "CartService");
    public final static QName CartServiceImplPort = new QName("http://cart.revature.com/", "CartServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SOAPGreeting/cartService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CartService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/SOAPGreeting/cartService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CartService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CartService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CartService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CartService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CartService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CartService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CartService
     */
    @WebEndpoint(name = "CartServiceImplPort")
    public CartService getCartServiceImplPort() {
        return super.getPort(CartServiceImplPort, CartService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CartService
     */
    @WebEndpoint(name = "CartServiceImplPort")
    public CartService getCartServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CartServiceImplPort, CartService.class, features);
    }

}
