package com.revature.cart;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-03-25T16:26:41.890-04:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://cart.revature.com/", name = "CartService")
@XmlSeeAlso({ObjectFactory.class})
public interface CartService {

    @WebMethod
    @RequestWrapper(localName = "addItem", targetNamespace = "http://cart.revature.com/", className = "com.revature.cart.AddItem")
    @ResponseWrapper(localName = "addItemResponse", targetNamespace = "http://cart.revature.com/", className = "com.revature.cart.AddItemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String addItem(
        @WebParam(name = "arg0", targetNamespace = "")
        com.revature.cart.Item arg0
    );

    @WebMethod
    @RequestWrapper(localName = "removeItem", targetNamespace = "http://cart.revature.com/", className = "com.revature.cart.RemoveItem")
    @ResponseWrapper(localName = "removeItemResponse", targetNamespace = "http://cart.revature.com/", className = "com.revature.cart.RemoveItemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean removeItem(
        @WebParam(name = "arg0", targetNamespace = "")
        com.revature.cart.Item arg0
    );

    @WebMethod
    @RequestWrapper(localName = "itemQuanitity", targetNamespace = "http://cart.revature.com/", className = "com.revature.cart.ItemQuanitity")
    @ResponseWrapper(localName = "itemQuanitityResponse", targetNamespace = "http://cart.revature.com/", className = "com.revature.cart.ItemQuanitityResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int itemQuanitity(
        @WebParam(name = "arg0", targetNamespace = "")
        com.revature.cart.Item arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
